#!/usr/bin/env bash

set -o noclobber -o noglob -o nounset -o pipefail

FILE_PATH="$1"
W=$2
H=$3
X=$4
Y=$5

MAX_IMAGE_WIDTH=1280
TIMEOUT_SECONDS=2

display_image() {
    local image="$1"
    if [[ "$TERM" =~ .*kitty.* ]]; then
        kitten icat --silent --stdin no --transfer-mode memory --place "${W}x${H}@${X}x${Y}" "$image" < /dev/null > /dev/tty
    elif command -v chafa &>/dev/null; then
        chafa --fill=block --symbols=block -c 256 --size "${W}x${H}" "$image" 2>/dev/null
    else
        echo 'supported image preview methods: kitty, chafa'
    fi
}

display_image_inplace() {
    display_image "$FILE_PATH"
}

display_image_cache() {
    display_image "$IMAGE_CACHE_PATH"
}

cache_if_needed_and_display_image() {
    local image="$1"
    local image_width="$(identify -format '%w' "$image")"
    if (( "$image_width" < "$MAX_IMAGE_WIDTH" )); then
        display_image "$image"
    else
        convert -geometry "$MAX_IMAGE_WIDTH"x -- "${image}" "${IMAGE_CACHE_PATH}" && display_image_cache
    fi
}

LF_CACHE="$HOME/.cache/lf_images"
[[ -d "$LF_CACHE" ]] || mkdir -p "$LF_CACHE"

# Use hash of absolute path and compare change time
IMAGE_CACHE_PATH="$LF_CACHE/$(echo "$FILE_PATH" | sha1sum | cut -f1 -d' ').jpg"

if [[ -f "$IMAGE_CACHE_PATH" ]]; then
    if [[ $(stat -c '%Y' "$FILE_PATH") -lt $(stat -c '%Y' "$IMAGE_CACHE_PATH") ]]; then
        display_image_cache && exit 1
    else
        rm "$IMAGE_CACHE_PATH"
    fi
fi

handle_mime() {
    local mimetype="$(file --dereference --brief --mime-type -- "${FILE_PATH}")"
    case "${mimetype}" in
        ## HTML
        text/html)
            # Preview as text conversion
            timeout $TIMEOUT_SECONDS w3m -dump "${FILE_PATH}" && exit 1
            timeout $TIMEOUT_SECONDS lynx -dump -- "${FILE_PATH}" && exit 1
            timeout $TIMEOUT_SECONDS elinks -dump "${FILE_PATH}" && exit 1
            exit 1;;

        ## Text
        text/* | */xml | application/json)
            # Syntax highlight
            highlight --out-format=ansi "${FILE_PATH}" && exit 1
            cat "${FILE_PATH}" && exit 1
            exit 1;;

        ## PDF
        application/pdf)
            pdftoppm -f 1 -l 1 \
                -singlefile \
                -jpeg -tiffcompression jpeg \
                -- "${FILE_PATH}" "${IMAGE_CACHE_PATH}" &&
            mv "${IMAGE_CACHE_PATH}.jpg" "${IMAGE_CACHE_PATH}" &&
            cache_if_needed_and_display_image "$IMAGE_CACHE_PATH"
            exit 1;;

        ## SVG
        image/svg+xml|image/svg)
            convert -- "${FILE_PATH}" "${IMAGE_CACHE_PATH}" && display_image_cache
            exit 1;;

        ## Image
        image/*)
            cache_if_needed_and_display_image "$FILE_PATH"
            exit 1;;

        ## Video
        video/*)
            # Get embedded thumbnail
            ffmpeg -i "${FILE_PATH}" -map 0:v -map -0:V -c copy "${IMAGE_CACHE_PATH}" && cache_if_needed_and_display_image "$IMAGE_CACHE_PATH" && exit 1

            # Get frame 10% into video
            local video_width=$(ffprobe -v error -show_entries stream=width -of default=nw=1:nk=1 "${FILE_PATH}" | head -n1)
            local width=$((video_width>MAX_IMAGE_WIDTH ? MAX_IMAGE_WIDTH : video_width))
            ffmpegthumbnailer -i "${FILE_PATH}" -o "${IMAGE_CACHE_PATH}" -s ${width} && display_image_cache && exit 1
            exit 1;;

        ## Audio
        audio/*)
            # Get embedded thumbnail
            ffmpeg -i "${FILE_PATH}" -map 0:v -map -0:V -c copy \
              "${IMAGE_CACHE_PATH}" && cache_if_needed_and_display_image "$IMAGE_CACHE_PATH" && exit 1
            exit 1;;

        ## OpenDocument
        application/vnd.oasis.opendocument*)
            # Preview as text conversion
            timeout $TIMEOUT_SECONDS odt2txt "${FILE_PATH}"
            exit 1;;

        ## Archives
        application/zip|application/gzip|application/zstd|application/x-tar)
            timeout $TIMEOUT_SECONDS atool --list -- "${FILE_PATH}" && exit 1
            timeout $TIMEOUT_SECONDS bsdtar --list --file "${FILE_PATH}" && exit 1
            exit 1;;

        application/x-7z-compressed)
            # Avoid password prompt by providing empty password
            timeout $TIMEOUT_SECONDS 7z l -p -- "${FILE_PATH}"
            exit 1;;

        application/vnd.rar)
            # Avoid password prompt by providing empty password
            timeout $TIMEOUT_SECONDS unrar lt -p- -- "${FILE_PATH}"
            exit 1;;
    esac
}

handle_extension() {
    case "$FILE_PATH" in
        *.mp3)
            # Sometimes mp3 files are not recognized for some reason
            # Get embedded thumbnail
            ffmpeg -i "${FILE_PATH}" -map 0:v -map -0:V -c copy \
              "${IMAGE_CACHE_PATH}" && display_image_cache && exit 1
            exit 1;;
    esac
}

handle_fallback() {
    echo '----- File Type Classification -----' && file --dereference --brief -- "${FILE_PATH}"
    exit 1
}

handle_mime
handle_extension
handle_fallback
